idd/pqacts/pqact.radars, threddsDev/pqacts/pqact.radars
fixing path issue in `pqact.radars`
=> fixing missing DATA_DIR path

idd/idd/forecastModels.xml, idd/pqacts/pqact.forecastModels, threddsDev/idd/forecastModels.xml, threddsDev/pqacts/pqact.forecastModels-HRS, threddsDev/pqacts/pqact.forecastModels-NGRID, threddsDev/pqacts/pqact.forecastModels-all
Remove all DGEX
Remove NAM 22km Alaska domain
=> Remove old models

idd/idd/forecastModels.xml
=> BUG: Remove vim oops from forecastModels catalog

threddsTest/testPointDatasets.xml
This PR adds a Station featureCollection on top of the METR netCDF files produced by ldm-alchemy.
=> ENH Add pfc for METR files produced by python

.gitattributes
=> force the use of lf on all OSs

threddsDev/build.info, threddsDev/catalog.xml, threddsDev/pqacts/pqact.modelsCmc, threddsDev/pqacts/pqact.modelsGdas, threddsDev/pqacts/pqact.ryan-test, threddsDev/pqacts/pqact.satellite, threddsDev/public/custom.css, threddsDev/templates/tdsTemplateFragments.html, threddsTest/build.info, threddsTest/catalog.xml, threddsTest/modelsNarr.xml, threddsTest/testDatasets.xml
make sure all data paths reference ${DATA_DIR} rather than /data/ldm/pub
sync up catalogs, pqacts in this repo to what is actually used on our machines
add new files needed for use in TDS 5.0 template system
=> A few cleanup items

threddsDev/idd/forecastProdsAndAna.xml
thredds-test had more data (specifically, mrms) than thredds-dev. This
PR syncs those catalogs.
=> sync thredds-test / thredds-dev forecast prods and analysis catalog

idd/idd/satellite.xml
ldm pqact entries managed outside the tds, so not included here...will
need to think about how to document those.
=> add goes 16/17 to satellite catalog

threddsTest/idd/satellite.xml, threddsTest/pqacts/pqact.satellite
- Improve LDM filing of the products
- Add to thredds-test
=> Fix up NPP data

.gitignore, .travis.yml, basic_checks.py
This PR will enable a check on Travis to make sure all xml files in the repo are at least well formed.
=> Check that all xml files are well formed

threddsTest/idd/forecastModels.xml, threddsTest/idd/forecastProdsAndAna.xml, threddsTest/modelsHrrr.xml
Sort in reverse lexicographical order such that newest "files" appear first in catalog listing.
This is a much better option for real-time data.
=> List grib collections with newest first

threddsTest/pqacts/pqact.ryan-test
Addresses Unidata/TdsConfig#81
=> File METARs to disk on thredds-test

threddsTest/pqacts/pqact.satellite
change from writing NOAA20 from NPP to NOAA20 dir
=> write noaa20 sat data to noaa20 dir

idd/idd/forecastModels.xml, idd/pqacts/pqact.forecastModels, thredds/idd/forecastModels.xml, threddsTest/idd/forecastModels.xml
addresses Unidata/TdsConfig#77, as well as adds missing GFS collections to thredds-test (data was already being filed by the LDM).
=> Cleanup and syncup

idd/idd/radars.xml, idd/radar/radarCollections.xml, threddsTest/idd/radars.xml, threddsTest/radar/radarCollections.xml
=> Update TDWR base reflectivity product code

idd/idd/forecastProdsAndAna.xml, idd/pqacts/README.txt, idd/pqacts/pqact.forecastProdsAndAna, thredds/pqacts/README.txt, threddsTest/idd/forecastProdsAndAna.xml, threddsTest/pqacts/README.txt
* Obtain grids from `HDS` feed instead of `NGRID`
* Update README files to add `HDS` feed to instructions for `pqact.forecastProdsAndAna`
=> Update National Blend of Models pqact and catalog entries

rdavm/wmsConfig.xml, remotetest/obsolete/public/wmsConfig.xml, remotetest/obsolete/wmsConfig.xml, remotetest/thredds/public/wmsConfig.xml, remotetest/thredds/wmsConfig.xml, startup/wmsConfig.xml, thredds/tdscapabilities/authTest.xml, wmsConfig.xml
Update the URL for the WMS config DTD referenced in all the `wmsConfig.xml` files.
=> Update URL of WMS config DTD.

threddsTest/idd/satellite.xml
threddstest/idd/satellite.xml is missing and end dataset tag
=> add missing end dataset tag

.gitignore, idd/idd/forecastModels.xml, thredds/idd/forecastModels.xml
- gitignore unzipped config folders
- remove service definitions, which were breaking ncss in TDS 5
=> remove services for upgrade to tds 5

awsL2/radar/RadarL2Stations.xml, idd/radar/RadarL2Stations.xml
=> remove NOP3 from stations

.github/workflows/checks.yml
Runs basic checks, build the config packages, and uploads them as a GHA artifact.
=> Add basic GitHub Actions workflow

.github/CODEOWNERS, idd/idd/forecastProdsAndAna.xml
Mistakenly left out of my last update.
Also add `CODEOWNERS` so that we can get automated review requests.
=> Add NBM Guam to TDS catalog

README.md
=> Update instructions in readme

threddsDev/notebooks/dataset_to_xarray_notebook.ipynb
- need to use thredds-dev to test the "accept" parameter of the notebook
=> add convert to xarray notebook to dev

thredds/casestudies/catalog.xml
add case study data for Yuan (requested by MSU)
=> add new case study

thredds/casestudies/catalog.xml
Add ML dataset to case studies and change dataset name
=> Add ML dataset

.github/workflows/checks.yml, idd/pqacts/pqact.forecastModels
GRIB1 was no longer showing up on HRS, needs to add NGRID.
=> Update patterns for recent changes

thredds/cybertraining/catalog.xml, threddsTest/remotetest/catalog.xml
* Add new DAP datasetScan to use security-constraint controlled restrictions
* Add new cybertraining dataset
=> thredds, thredds-test catalog updates

idd/idd/satellite.xml
* remove GRB17 datasets
* remove WMS from GRB services
=> Satellite catalog changes

.github/workflows/checks.yml, idd/idd/goes/goes16.xml, idd/idd/goes/goes17.xml, idd/idd/goes/goes18.xml, idd/idd/goes/goes19.xml, idd/idd/satellite.xml
* Add individual catalogs for each GOES platform
* Include HTTPServer service for GOES datasets (accidentally removed with WMS)
* Re-enable NESDIS Blended Satellite Products
* Update documentation metadata
=> Satellite Catalog Improvements
