Unidata/TdsConfig

thredds/threddsConfig.xml

NCSS requests on thredds.ucar.edu seem to be hammering the machine. We also have issues with HDF5 not properly running in single threaded mode, and we are getting file collisions. This commit is to see if limiting "big" ncss requests will help the stability of the server until we get a fix in on the java side.

limit ncss requests on thredds.ucar.edu

---

threddsDev/pqacts/pqact.satellite
threddsTest/testDatasets.xml

addresses Unidata/TdsConfig#27
update to account for path change in ldm-alchemy. Therefore,
this commit depends on Unidata/ldm-alchemy#2

test ncml agg for goes 16 data

---

idd/idd/forecastModels.xml

A `path=grib/NCEP/GFS/Global_onedeg` entry already existed prior to the addition of the NOAAPORT grids, so this make sure the paths are unique. Previously, the TDS skipped over these NOAAPORT grids because of the path conflict.

Make sure path is unique

---

idd/idd/forecastModels.xml

There is a leading space for the NAVGEM that I noticed when parsing catalog XML in Python for the THREDDSewingMachine. Atom also took care of some whitespace it looks like.

Remove leading space in NAVGEM model name

---

idd/idd/forecastModels.xml
threddsDev/idd/forecastModels.xml

Correct the metadata for the forecast grid output time for the NAM 12km grids from CONDUIT.

Add current NAM 12km CONDUIT time information

---

idd/idd/obsData.xml
idd/idd/radars.xml

`addId` elements cause xml validation errors on startup. This PR removes those elements.

remove addId elements

---

threddsTest/testPointDatasets.xml

This PR adds a test `datasetScan` element for some NWC files for Yuan.

add NWC test point dataset for Yuan

---

threddsTest/pqacts/README.txt
threddsTest/pqacts/pqact.radars
threddsTest/pqacts/pqact.satellite
threddsTest/tdsconfig_tools/config_update.sh
threddsTest/tdsconfig_tools/pqact_diff.sh

This PR aims to help manage the sharing of pqacts between the TDS (managed via TdsConfig) and the LDM on lead (i.e. threddsTest). This also fixes an issue with LDM logging when executing actions in the pqact files with sh.

Facilitate pqact sharing between tomcat and ldm on lead

---

idd/pqacts/pqact.forecastModels

The products on CONDUIT have an extra '/' in the path now--the lack of which was causing us not to file products.
This was documented in [Service Change Notice 19-40](https://www.weather.gov/media/notification/scn19-40gfs_v15_1.pdf)

Fix pqacts for FV3

---

threddsTest/idd/satellite.xml
threddsTest/pqacts/pqact.satellite

Looks like NOAAPORT has moved/is moving some things from NPP to NOAA-20:
* NUCAPS Soundings (already done): https://www.weather.gov/media/notification/scn19-59nucaps_soundings.pdf
* VIIRS Near-constant contrast (NCC) imagery: https://www.weather.gov/media/notification/scn19-66viirs_ncc_sbn.pdf
The first one is already done, and really on needs some catalog updates for naming--the data are matching the same pattern. For the NCC, the new data started yesterday, so I went ahead and replaced the old data with the new. The old data will stop a month from now, at which point we may need to remove the Alaska imagery, at least the NCC.
@lesserwhirls I'll leave to you to merge (and please update the server?) when this isn't at risk of breaking a workshop.

Updates for move from NPP to NOAA-20

---

idd/idd/satellite.xml

A whole bunch of legacy products are no more, like sounders and many of the derived products, so remove them. Also remove channels that are no longer available.
There are still some NHEM composites showing up, so keep vis, IR, WV.
Also, I went ahead and added a few derived products in GINI (rainfall rate, percent normal TPW) that were on disk but not served. While these particular GINI products are slated to go away, they will be replaced by equivalent composites based on newer satellites. We can switch over to those here when NOAAPORT does.

Update catalog for GINI changes

---

idd/pqacts/pqact.forecastModels

As per the message sent via the CODUIT list on 06/28/2022:
> *As a reminder for CONDUIT users*,
> *the impact of the change to all model data to use version numbers means
> that data will be inserted into the CONDUIT LDM feeds at NCEP with a
> version number in its directory path instead of "prod". These are the same
> version numbers used for model data on our NOMADS service
> <https://nomads.ncep.noaa.gov/>.*
> (Example: data/nccf/com/gfs/*prod*/gfs.20220626/12/atmos/gfs.t12z.pgrb2.0p25.f000
> *--->* data/nccf/com/gfs/*v16.2*
> /gfs.20220626/12/atmos/gfs.t12z.pgrb2.0p25.f000)

prod --> .* for GFS

---

awsL2/idd/radars.xml
idd/idd/forecastProdsAndAna.xml
idd/idd/radars.xml
idd/idd/satellite.xml
rdavm/catalog_ds131.1.xml
rdavm/catalog_ds298.0.xml
rdavm/catalog_ds316.0.xml
rdavm/catalog_ds502.0.xml
rdavm/catalog_ds601.0.xml
rdavm/catalog_ds631.0.xml
thredds/tdscapabilities/authTest.xml
threddsTest/cf_examples.xml

Fix the catalog service base paths for ncss to use /ncss/grid/ or /ncss/point/ instead of /ncss/

Fix ncss service base paths

---

idd/idd/textProds.xml

This is a workaround, I don't think that it should be necessary to define a compound service to use one of the base services. If you agree, I will open a GH issue in TDS to fix the actual bug (and add a task to remove this workaround here).
This should fix the error we are currently getting on [thredds-dev](https://thredds-dev.unidata.ucar.edu/thredds/catalog/noaaport/text/metar/catalog.html):
```
Caused by: java.lang.AssertionError
at thredds.server.catalogservice.CatalogViewContextParser.makeFileServerUrl(CatalogViewContextParser.java:317)
at thredds.server.catalogservice.CatalogViewContextParser.getCatalogItemHref(CatalogViewContextParser.java:231)
at thredds.server.catalogservice.CatalogViewContextParser.populateItemContext(CatalogViewContextParser.java:135)
at …
```

Workaround to fix HTTPServer service in textProds

---

idd/pqacts/pqact.satellite

Was not quite the right invocation of the strip_header script. Somehow this was resulting in the raw products (including WMO header) being written to disk. Also this had the `-d` (decompress) flag being passed, which wouldn't run correctly for this data.

Fix pqact for blended satellite products

---

idd/radar/radarCollections.xml

Since the production machine is still using the old perl-based handler, we only have filenames with time out to the minute, not second.

Fix level2 data serving through the radar server

---

idd/idd/forecastProdsAndAna.xml

Convert from hours to minutes so that all grib files in collection have the same units, and so the "best" does not have "mixed_interval" times units/ variable names.
I tested this catalog change with the latest snapshot on thredds-dev.
Any preference for minutes or hours as the unit?

Use timeUnitConverter

---

idd/radar/radarCollections.xml

* Add new super-res vel/reflectivity products
* Add the X/Y/Z elevation variations that cover new lower elevation scans
* Re-label from "Tilt N" to list the actual NWS documented elevation angle (range)
Since we still seem to be getting some of the legacy products (I see files on disk within the last 30 days), I didn't remove any yet.
These are served from the Radar Query Service as metadata, and at least Siphon can use this to optionally validate a query. This *might* also be used somewhere to populate the IDV level 3 chooser, though if it did I'd have expected to hear awhile ago.

Update radar metadata

---

threddsTest/notebooks/normalized_dataset.ipynb
threddsTest/notebooks/standardized_dataset.ipynb

This PR adds notebooks for visualization of only preprocessed datasets that were included on threddsTest by https://github.com/Unidata/TdsConfig/pull/127 . 
The inclusion of these notebooks also closes the issue https://github.com/Unidata/netcdf-java/issues/1206 .

Add notebooks for preprocessed datasets

---

idd/pqacts/pqact.satellite

The proposed directory structure would add a `Radio_Occultation/COSMIC/PlanetIQ` directory to satellite products, with subdirectories made by the variable names and `YYYYJJJ` strings in the Product IDs.
Reference this message for product details: https://www.unidata.ucar.edu/mailing_lists/archives/ldm-users/2023/msg00116.html

Add COSMIC RO data to pqact.satellite

---

idd/pqacts/pqact.forecastProdsAndAna

- Currently the TDS doesn't show MRMS data until each hour is finished being written, since each file shows as `lastModified` less than the `olderThan` period.
- This PR breaks the data into 10 minute files, so data will appear on the TDS more regularly

break mrms base reflectivity into 10 minute binned files

---

thredds/casestudies/catalog.xml

Change moisture transport case study from aggregation to grib feature collection. You can already view this change on thredds-test [here](https://thredds-test.unidata.ucar.edu/thredds/catalog/casestudies/moisture_transport/nam/catalog.html).

Update case study

---

thredds/templates/tdsTemplateFragments.html
threddsTest/templates/tdsTemplateFragments.html

Add custom template fragments for each of the three unidata thredds servers. Except for  thredds-dev, the ones currently used were not in git and the thredds-dev one seemed outdated. I copied the currently used version on [thredds-test](https://thredds-test.unidata.ucar.edu/thredds/catalog/catalog.html) for each of the three servers, with the banner text being the only difference between them ("Welcome to the NSF Unidata (Test/Development) THREDDS Data Server!")

Add custom template fragments

---

threddsTest/preprocessed/catalog.xml

Add GFS datasets with NcML classifier applied to the relative humidity and temperature as a demo of the classifier. Remove other variables so only the classified ones appear. This change is already on thredds-test [here](https://thredds-test.unidata.ucar.edu/thredds/catalog/classified/grib/NCEP/GFS/CONUS_20km/catalog.html)

Add data with classifier

---

build.py

* Ignore .DS_Store files in config directories when constructing config.zip files
* Remove SunOS check in fetch.sh script
* Do not ignore TLS cert when fetching config.zip from the artifacts server

Build improvements
